CREATE ROLE myErp_user WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'md52a3f10a7cac0491c584c3d73f0f57c94';

CREATE DATABASE myErp
    WITH
    OWNER = myErp_user
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
