version: '2'
services:
  myerp.db:
    image: postgres:9.4
    restart: always
    ports:
      - "127.0.0.1:9032:5432"
    environment:
      - POSTGRES_DB=myerp
      - POSTGRES_USER=myerp_user
      - POSTGRES_PASSWORD=myerp
    volumes:
#Postgres       - "./00_create_db.sql:/init/db/docker-entrypoint-initdb.d/00_create_db.sql"
#Postgres       - "./01_create_schema.sql:/init/db/docker-entrypoint-initdb.d/01_create_schema.sql"
#Postgres       - "./02_create_tables.sql:/init/db/docker-entrypoint-initdb.d/02_create_tables.sql"
#Postgres       - "./21_insert_data_demo.sql:/init/db/docker-entrypoint-initdb.d/21_insert_data_demo.sql"
       - "./init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
       - "./postgres-data:/var/lib/postgresql/data"
volumes:
  postgres-data:      
