language: java
jdk:
  - oraclejdk8
dist: trusty
before_script: 
  - cd src
addons:
  sonarcloud:
    organization: "glescroel"
#    token:
#      secure: "**************************" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=GLescroel_myErp -Dsonar.login=ae2e527979c2c9445d5c80faa13b734aaa8e39f8
