language: java
jdk:
  - oraclejdk8
dist: trusty

services:
#  - docker
  - postgresql

before_script:
#  - cd ./docker/dev/
#  - docker-compose up -d
#  - cd ../../src
  - psql -c 'create database myerp;' -U postgres
  - psql -c "create user myerp_user with password 'myerp';" -U postgres
  - psql -c 'grant all privileges on database myerp to myerp_user;' -U postgres
  - cd ./docker/dev/init/db/docker-entrypoint-initdb.d/
  - psql myerp -U myerp_user -f ./01_create_schema.sql
  - psql myerp -U myerp_user -f ./02_create_tables.sql
  - psql myerp -U myerp_user -f ./21_insert_data_demo.sql
#  - psql -c 'GRANT USAGE ON SCHEMA myerp TO myerp_user;' -U postgres
#  - psql -c 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA myerp to myerp_user;' -U postgres
#  - psql -c 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA myerp TO myerp_user;' -U postgres
#  - psql -c '\dn;' -U postgres#  
  - cd ../../../../../src

addons:
  sonarcloud:
    organization: "glescroel"
#    token:
#      secure: "**************************" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=GLescroel_myErp -Dsonar.login=ae2e527979c2c9445d5c80faa13b734aaa8e39f8

after_script:
  - cd ../docker/dev
  - docker-compose stop
  - docker-compose rm -f
