language: java
jdk:
  - oraclejdk8
dist: trusty
before_script: 
  - cd src
addons: 
  sonarcloud: 
    organization: "GLescroel" 

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=GLescroel_myErp -Dsonar.login=1d59563522f070cbc907ccb02cd602994b390b25
